project:
  name: aforix

timezone: America/Montevideo

raw_data_path_dir: "D:\\Dropbox\\MADI\\DINAGUA_SL\\03-Proces_Info_DIN\\01-Salidas_campo"
subfolder_raw_data_word_dir: "Salida"
subsubfolder_raw_data_word_dir_FT: "flowtracker_S13"

flowtracker_spec_path: "configs/specs/flowtracker_spec_v1.yml"
registry_path: "configs/registries/registry.yml"

subsubfolder_raw_data_word_dir_ML: "molinete_S14"
molinete_sheet_name: "CALCULO"

subsubfolder_raw_data_word_dir_NIV: "Output_NIVUS_S13"

build_groups:
  output_dir: "database/data_groups"

  sources:
    flowtracker: "runs/ingest_flowtracker/20260428_194305"
    molinete: "runs/ingest_molinete/20260428_005839"
    nivus: "runs/ingest_nivus/20260428_164739"

normalize_summary:
  input_file: "database/data_groups/Summary/summary_all.csv"
  output_file: "database/normalized/Summary/summary_normalized.csv"