instrument: nivus

tables:

  Summary:
    canonical_name: summary

    columns:
      station_id:
        source: station_id
        dtype: string

      station_name:
        sources:
          - station_name
          - name
        dtype: string

      measurement_date:
        source: measurement_date
        dtype: string

      measurement_time:
        source: measurement_time
        dtype: string

      instrument:
        sources:
          - instrument
          - source
        dtype: string

      source_file:
        sources:
          - source_file
          - input_file
          - input_path
        dtype: string

      source_run_dir:
        source: source_run_dir
        dtype: string

      run_id:
        source: run_id
        dtype: string

      q_total_m3s:
        source: __derived__
        dtype: float

      q_total_ls:
        sources:
          - q_total_ls
          - total_discharge_ls
          - q [l/s]
        dtype: float

      area_total_m2:
        sources:
          - area_total_m2
          - total_area_m2
          - a [m²]
        dtype: float

      width_total_m:
        sources:
          - width_total_m
          - width_m
          - w [m]
        dtype: float

      velocity_mean_m_s:
        sources:
          - velocity_mean_m_s
          - mean_velocity_ms
          - v_mean [m/s]
        dtype: float

      depth_mean_m:
        sources:
          - depth_mean_m
          - mean_depth_m
          - h_mean [m]
        dtype: float

      temperature_c:
        sources:
          - temperature_c
          - t [°C]
        dtype: float

      min_depth_m:
        source: h_min [m]
        dtype: float

      max_depth_m:
        source: h_max [m]
        dtype: float

      min_velocity_m_s:
        source: v_min [m/s]
        dtype: float

      max_velocity_m_s:
        source: v_max [m/s]
        dtype: float

      wetted_perimeter_m:
        source: p [m]
        dtype: float

      hydraulic_radius_m:
        source: rh [m]
        dtype: float

      n_points:
        source: points
        dtype: int

      n_sections:
        source: sections
        dtype: int

    derived:
      q_total_m3s:
        from: q_total_ls
        operation: divide
        value: 1000

    required:
      - station_id
      - measurement_date
      - measurement_time
      - instrument
      - q_total_ls

    transforms:
      - name: strip_strings
      - name: numeric_commas_to_dots
      - name: enforce_dtypes

    qc:
      non_negative:
        #- q_total_m3s
        #- q_total_ls
        - area_total_m2
        - width_total_m
        - depth_mean_m


  Points:
    canonical_name: points

    columns:
      station_id:
        source: station_id
        dtype: string

      station_name:
        sources:
          - station_name
          - name
        dtype: string

      measurement_date:
        source: measurement_date
        dtype: string

      measurement_time:
        source: measurement_time
        dtype: string

      instrument:
        sources:
          - instrument
          - source
        dtype: string

      source_file:
        sources:
          - source_file
          - input_file
          - input_path
        dtype: string

      source_run_dir:
        source: source_run_dir
        dtype: string

      run_id:
        source: run_id
        dtype: string

      point_index:
        sources:
          - point_index
          - index
        dtype: int

      point_label:
        sources:
          - point_label
          - index
        dtype: string

      distance_m:
        sources:
          - distance_m
          - pos [m]
        dtype: float

      depth_m:
        sources:
          - depth_m
          - h [m]
        dtype: float

      velocity_mean_m_s:
        sources:
          - velocity_mean_m_s
          - v [m/s]
        dtype: float

      area_m2:
        source: area_m2
        dtype: float

      q_m3s:
        source: q_m3s
        dtype: float

      q_ls:
        source: q_ls
        dtype: float

      percent_q:
        sources:
          - percent_q
          - tq [%]
          - atq [%]
          - hq [%]
        dtype: float

      temperature_c:
        sources:
          - temperature_c
          - t [°C]
        dtype: float

      measured_depth_m:
        source: h_meas [m]
        dtype: float

      measurement_duration_s:
        source: mtime [s]
        dtype: float

    required:
      - station_id
      - measurement_date
      - measurement_time
      - instrument
      - point_index
      - distance_m
      - depth_m

    transforms:
      - name: strip_strings
      - name: numeric_commas_to_dots
      - name: enforce_dtypes

    qc:
      non_negative:
        - distance_m
        - depth_m
        - measured_depth_m


  Sections:
    canonical_name: sections

    columns:
      station_id:
        source: station_id
        dtype: string

      station_name:
        source: station_name
        dtype: string

      measurement_date:
        source: measurement_date
        dtype: string

      measurement_time:
        source: measurement_time
        dtype: string

      instrument:
        sources:
          - instrument
          - source
        dtype: string

      source_file:
        sources:
          - source_file
          - input_file
          - input_path
        dtype: string

      source_run_dir:
        source: source_run_dir
        dtype: string

      run_id:
        source: run_id
        dtype: string

      section_index:
        sources:
          - section_index
          - index
        dtype: int

      distance_m:
        sources:
          - distance_m
          - pos [m]
        dtype: float

      q_ls:
        sources:
          - q_ls
          - q [l/s]
        dtype: float

      q_m3s:
        source: __derived__
        dtype: float

      percent_q:
        sources:
          - percent_q
          - factor [%]
        dtype: float

      width_m:
        sources:
          - width_m
          - w [m]
        dtype: float

      depth_m:
        sources:
          - depth_m
          - h [m]
        dtype: float

      velocity_mean_m_s:
        sources:
          - velocity_mean_m_s
          - v [m/s]
        dtype: float

    derived:
      q_m3s:
        from: q_ls
        operation: divide
        value: 1000

    required:
      - station_id
      - measurement_date
      - measurement_time
      - instrument
      - section_index
      - distance_m
      - q_ls

    transforms:
      - name: strip_strings
      - name: numeric_commas_to_dots
      - name: enforce_dtypes

    qc:
      non_negative:
        - distance_m
        - width_m
        - depth_m
        #- q_ls
        #- q_m3s


  Gates:
    canonical_name: gates

    columns:
      station_id:
        source: station_id
        dtype: string

      station_name:
        source: station_name
        dtype: string

      measurement_date:
        source: measurement_date
        dtype: string

      measurement_time:
        source: measurement_time
        dtype: string

      instrument:
        sources:
          - instrument
          - source
        dtype: string

      source_file:
        sources:
          - source_file
          - input_file
          - input_path
        dtype: string

      source_run_dir:
        source: source_run_dir
        dtype: string

      run_id:
        source: run_id
        dtype: string

      point_index:
        source: point_index
        dtype: int

      gate_index:
        sources:
          - gate_index
          - index
        dtype: int

      gate_position_m:
        sources:
          - gate_position_m
          - pos [m]
        dtype: float

      velocity_mean_m_s:
        sources:
          - velocity_mean_m_s
          - v [m/s]
        dtype: float

      original_velocity_m_s:
        source: orig [m/s]
        dtype: string

    required:
      - station_id
      - measurement_date
      - measurement_time
      - instrument
      - point_index
      - gate_index
      - gate_position_m

    transforms:
      - name: strip_strings
      - name: numeric_commas_to_dots
      - name: enforce_dtypes

    qc:
      non_negative:
        - gate_position_m